import { NgModule } from "@angular/core"
import { MdCardModule, MdIconModule, MdLineModule, MdListModule, MdMenuModule, MdTabsModule, MdChipsModule,
         MdInputModule, MdRadioModule, MdButtonModule, MdDialogModule, MdOptionModule, MdRippleModule,
         MdSelectModule, MdSliderModule, MdSidenavModule, MdToolbarModule, MdTooltipModule, MdCheckboxModule,
         MdGridListModule, MdSnackBarModule, MdDatepickerModule, MdProgressBarModule, MdSlideToggleModule,
         MdAutocompleteModule, MdButtonToggleModule, MdProgressSpinnerModule } from "@angular/material"

@NgModule({
  imports: [
    MdCardModule,
    MdIconModule,
    MdLineModule,
    MdListModule,
    MdMenuModule,
    MdTabsModule,
    MdChipsModule,
    MdInputModule,
    MdRadioModule,
    MdButtonModule,
    MdDialogModule,
    MdOptionModule,
    MdRippleModule,
    MdSelectModule,
    MdSliderModule,
    MdSidenavModule,
    MdToolbarModule,
    MdTooltipModule,
    MdCheckboxModule,
    MdGridListModule,
    MdSnackBarModule,
    MdDatepickerModule,
    MdProgressBarModule,
    MdSlideToggleModule,
    MdAutocompleteModule,
    MdButtonToggleModule,
    MdProgressSpinnerModule,
  ],
  exports: [
    MdCardModule,
    MdIconModule,
    MdLineModule,
    MdListModule,
    MdMenuModule,
    MdTabsModule,
    MdChipsModule,
    MdInputModule,
    MdRadioModule,
    MdButtonModule,
    MdDialogModule,
    MdOptionModule,
    MdRippleModule,
    MdSelectModule,
    MdSliderModule,
    MdSidenavModule,
    MdToolbarModule,
    MdTooltipModule,
    MdCheckboxModule,
    MdGridListModule,
    MdSnackBarModule,
    MdDatepickerModule,
    MdProgressBarModule,
    MdSlideToggleModule,
    MdAutocompleteModule,
    MdButtonToggleModule,
    MdProgressSpinnerModule,
  ]
})
export class MaterialModule {}